version: '3'
services:
  master-webserver:
    image: nginx:1.14
    networks:
      - master-webserver
      - php-apache-1
      - php-fpm-1
      - php-fpm-1-admin
      - pgadmin4
      - phpmyadmin
      - python-uwsgi-1
    volumes:
     - ./master-webserver/sites-enabled:/etc/nginx/conf.d:ro
     - ./master-webserver/certs:/etc/nginx/certs:ro
     - ./www:/var/www:ro
     - ./master-webserver/cache:/cache
    ports:
     - "85:85"
     - "443:443"
    restart: always
  php-apache-1:
    image: php:7.3-apache-stretch
    networks:
      - php-apache-1
    read_only: true
    volumes:
     - ./www/php-apache-1:/var/www/html/:ro
     - ./www/php-apache-1/uploads:/var/www/html/uploads/
    tmpfs:
      - /run/apache2/
    # ports:
    #   - "86:80"
    restart: always
  php-fpm-1:
    networks:
      - php-fpm-1
      - mysql-1
    image: php:7.3-fpm-stretch
    volumes:
     - ./www/php-fpm-1:/var/www/html/:ro
    restart: always
  php-fpm-1-admin:
    networks:
      - php-fpm-1-admin
      - mysql-1
    image: php:7.3-fpm-stretch
    volumes:
     - ./www/php-fpm-1:/var/www/html/
    restart: always
  mysql-1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mysql-1
    volumes:
     - ./mysql-1/datadir:/var/lib/mysql
    # ports:
    #   - "33061:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
  postgresql-1:
    image: postgres:11
    networks:
      - postgresql-1
    volumes:
     - ./postgresql-1/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    networks:
      - phpmyadmin
      - mysql-1
    environment:
      - PMA_HOST=mysql-1
    # ports:
    #  - 8081:80
    volumes:
     - /sessions
    restart: always
  pgadmin4:
    build: ./pgadmin4
    networks:
      - pgadmin4
      - postgresql-1
    image: lamp/pgadmin4
    environment:
      - DEFAULT_USER=postgres
      - DEFAULT_PASSWORD
    restart: always
  python-uwsgi-1:
    build: ./python-uwsgi
    image: lamp/python-uwsgi
    networks:
      - python-uwsgi-1
      - postgresql-1
    volumes:
      - ./python-uwsgi-1/foobar.py:/usr/src/app/foobar.py:ro
    command:
      - uwsgi
      - --uid
      - www-data      # user to log in
      - -p3           # number of python processes
      - --lazy-apps   # fork early (avoid sharing same DB connection)
      - --uwsgi-socket
      - 0.0.0.0:3031  # Listen on 3031
      - -i            # don't use multiple interpreters
      - --py-autoreload
      - "1"           # watch the python file and reload
      - --wsgi-file
      - foobar.py     # name of the python file to load
    restart: always
  sftp-php-apache-1:
    image: atmoz/sftp:debian-stretch
    networks:
      - sftp-php-apache-1
    volumes:
      - ./www/php-apache-1:/home/admin/php-apache-1
    ports:
      - "2201:22"
    command: admin:$$1$$Kv3LD.h5$$Zzcq9QemRAq/.AD8QRhYr1:e:1000
    restart: always
  sftp-python-uwsgi-1:
    image: atmoz/sftp:debian-stretch
    networks:
      - sftp-python-uwsgi-1
    volumes:
      - ./www/python-uwsgi-1:/home/admin/python-uwsgi-1
    ports:
      - "2202:22"
    command: admin:$$1$$Iuu6OCAV$$biLkSdg7888B9tkm8ca.p1:e:1000
    restart: always
  ftpd-php-apache-1:
    image: stilliard/pure-ftpd
    networks:
      - ftpd-php-apache-1
    ports:
      - "2101:21"
      - "21010-21019:21010-21019"
    expose:
      - "21010-21019"
    volumes:
     - ./www/php-apache-1:/var/www/html/
    environment:
      - PUBLICHOST=localhost  # Replace this with your server public IP
      - FTP_PASSIVE_PORTS=21010:21019
      - FTP_USER_HOME=/var/www/html/
      - FTP_USER_NAME=admin
      - FTP_USER_PASS=${FTP_PHP_APACHE_1_PASS-}
    restart: always
networks:
  default: {internal: true}
  master-webserver: {}
  php-apache-1: {internal: true}
  php-fpm-1: {internal: true}
  mysql-1: {internal: true}
  postgresql-1: {internal: true}
  phpmyadmin: {internal: true}
  pgadmin4: {internal: true}
  python-uwsgi-1: {internal: true}
  sftp-php-apache-1: {}
  sftp-python-uwsgi-1: {}
  ftpd-php-apache-1: {}
  php-fpm-1-admin: {}
